In [1]:
import pandas as pd
import numpy as np

In [3]:
# 读取数据
column_name=['Sample code number', 'Clump Thickness',' Uniformity of Cell Size','Uniformity of Cell Shape','Marginal Adhesion',                                             
    'Single Epithelial Cell Size', 'Bare Nuclei','Bland Chromatin','Normal Nucleoli ','Mitoses ','Class']

data=pd.read_csv('breast-cancer-wisconsin.data',names=column_name)

In [4]:
data.head()

Sample code number  Clump Thickness   Uniformity of Cell Size  \
0             1000025                5                         1   
1             1002945                5                         4   
2             1015425                3                         1   
3             1016277                6                         8   
4             1017023                4                         1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli   Mitoses   Class  
0           1                3                 1         1      2  
1          10                3                 2         1      2  
2           2                3                 1         1      2  
3           4                3                 7         1      2  
4           1                3                 1         1      2

In [5]:
# 2 缺失值处理
# 1）缺失值替换np.nan
data=data.replace(to_replace='?',value=np.nan)
# 2）缺失值处理
data.dropna(inplace=True)

In [7]:
data.isnull().any()

Sample code number             False
Clump Thickness                False
 Uniformity of Cell Size       False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [8]:
# 3划分数据集
from sklearn.model_selection import train_test_split
# 筛选特征值和目标值
x=data.iloc[:,1:-1]
y=data['Class']
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [11]:
# 4标准化
from sklearn.preprocessing import StandardScaler
transfer=StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [12]:
x_train

array([[-1.21570315, -0.72675115, -0.76585108, ..., -0.19975295,
        -0.61446994, -0.3499284 ],
       [-0.52217667, -0.72675115, -0.42984787, ..., -0.60240458,
        -0.61446994, -0.3499284 ],
       [ 0.51811304, -0.72675115, -0.76585108, ..., -0.19975295,
        -0.61446994, -0.3499284 ],
       ...,
       [ 1.21163951,  1.55605001,  1.25016822, ...,  1.41085354,
         1.65824447,  3.31894543],
       [ 0.1713498 , -0.72675115, -0.76585108, ..., -1.0050562 ,
        -0.61446994, -0.3499284 ],
       [-0.52217667, -0.72675115, -0.76585108, ..., -0.60240458,
        -0.61446994, -0.3499284 ]])

In [13]:
# 5 逻辑回归预估器流程
from sklearn.linear_model import LogisticRegression
estimator=LogisticRegression()
estimator.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
# 逻辑回归参数 ：回归系数和偏置
estimator.coef_

array([[1.22468141, 0.33176107, 0.67958323, 0.85519438, 0.44753431,
        1.25542461, 1.04816139, 0.2516021 , 0.59925736]])

In [15]:
estimator.intercept_

array([-0.77966992])

In [16]:
#  6模型评估
y_predict=estimator.predict(x_test)
print('y_predict:\n',y_predict)
print(y_test==y_predict)
# 方法2：计算准确率
score=estimator.score(x_test,y_test)
print('准确率为：\n',score)

y_predict:
 [2 4 4 2 2 2 4 2 2 4 2 2 4 2 2 4 4 2 4 2 4 4 2 2 4 4 2 2 4 2 2 4 2 2 2 4 2
 2 2 2 4 2 4 2 4 4 4 2 2 4 2 4 2 4 4 2 2 2 2 2 2 2 4 2 2 2 2 4 4 2 2 2 2 2
 2 2 2 4 2 4 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2 4 4 4 2 4 4 2 2 4 4 2 2 2 2
 2 2 2 2 2 2 4 2 4 4 4 2 4 2 2 4 2 2 2 2 2 2 4 2 2 2 2 4 4 2 2 2 4 2 2 2 2
 2 2 2 2 2 2 4 2 2 2 4 4 2 2 2 4 2 2 2 4 4 2 2]
143    True
323    True
229    True
587    True
185    True
       ... 
9      True
302    True
591    True
24     True
37     True
Name: Class, Length: 171, dtype: bool
准确率为：
 0.9824561403508771


In [22]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
report=classification_report(y_test,y_predict,labels=[2,4],target_names=['良性','恶性'])

In [20]:
print(report)

              precision    recall  f1-score   support

          良性       0.99      0.98      0.99       119
          恶性       0.96      0.98      0.97        52

    accuracy                           0.98       171
   macro avg       0.98      0.98      0.98       171
weighted avg       0.98      0.98      0.98       171



In [23]:
# 混淆矩阵
con=confusion_matrix(y_test,y_predict)

In [24]:
print(con)

[[117   2]
 [  1  51]]


In [26]:
# y-true：每个样本的真实类别，必须为0（反例），1正例）标记
y_true=np.where(y_test>3,1,0)

In [28]:
from sklearn.metrics import roc_auc_score

In [29]:
roc_auc_score(y_true,y_predict)

0.9819812540400775